# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- task: CmdLine@2
  displayName: 'Push to Azure Repos'
  inputs:
    script: |
      git config --global user.email "aunrazaq123@gmail.com"
      git config --global user.name "Aun-Raza"
      git remote add azure https://araza32@dev.azure.com/araza32/StringLibrary/_git/StringLibrary
      git push -u azure HEAD:main

